import type { Metadata } from "next";
import { Oswald, Source_Sans_3 } from "next/font/google";
import "@/styles/globals.scss";


const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin", "cyrillic"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { LanguageProvider } from "@/context/LanguageContext.tsx";
import { UIProvider } from "@/context/UIContext.tsx";
import { Header } from "@/components/layout/Header/Header.tsx";
import { Footer } from "@/components/layout/Footer/Footer.tsx";
import { i18n } from "@/i18n-config.ts";
import { Language } from "@/types/language.ts";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const currentLang = lang as Language;

  return (
    <html lang={lang} className={`${oswald.variable} ${sourceSans.variable}`}>
      <body >
        <LanguageProvider initialLang={currentLang}>
          <UIProvider>
            <Header />
            <main className='main-flex'>
              {children}
            </main>
            <Footer />
          </UIProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
