# Generated by Django 6.0.5 on 2026-05-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('media_src', models.CharField(max_length=500)),
                ('date_label_ru', models.CharField(max_length=120)),
                ('date_label_bg', models.CharField(max_length=120)),
                ('date_label_en', models.CharField(max_length=120)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_bg', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_ru', models.JSONField(default=list)),
                ('content_bg', models.JSONField(default=list)),
                ('content_en', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_bg', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_ru', models.TextField()),
                ('content_bg', models.TextField()),
                ('content_en', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('item_type', models.CharField(choices=[('course', 'Course'), ('webinar', 'Webinar')], max_length=16)),
                ('slug', models.SlugField(unique=True)),
                ('media_src', models.CharField(max_length=500)),
                ('poster', models.CharField(blank=True, max_length=500)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_bg', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_bg', models.TextField()),
                ('description_en', models.TextField()),
                ('start_date_ru', models.CharField(max_length=120)),
                ('start_date_bg', models.CharField(max_length=120)),
                ('start_date_en', models.CharField(max_length=120)),
                ('price_ru', models.CharField(max_length=120)),
                ('price_bg', models.CharField(max_length=120)),
                ('price_en', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('experienced', 'Experienced'), ('business', 'Business')], max_length=20)),
                ('goal', models.CharField(choices=[('launch', 'Launch'), ('taxes', 'Taxes'), ('profession', 'Profession'), ('optimization', 'Optimization')], max_length=20)),
                ('item_format', models.CharField(choices=[('online', 'Online'), ('live', 'Live'), ('offline', 'Offline')], max_length=20)),
                ('level_label_ru', models.CharField(max_length=120)),
                ('level_label_bg', models.CharField(max_length=120)),
                ('level_label_en', models.CharField(max_length=120)),
                ('goal_label_ru', models.CharField(max_length=120)),
                ('goal_label_bg', models.CharField(max_length=120)),
                ('goal_label_en', models.CharField(max_length=120)),
                ('format_label_ru', models.CharField(max_length=120)),
                ('format_label_bg', models.CharField(max_length=120)),
                ('format_label_en', models.CharField(max_length=120)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_bg', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_bg', models.TextField()),
                ('description_en', models.TextField()),
                ('education_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='content.educationitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
