# Generated by Django 6.0.5 on 2026-05-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('consultation_format', models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority')], max_length=16)),
                ('meeting_type', models.CharField(choices=[('sofia', 'Sofia'), ('zoom', 'Zoom')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('selected_date', models.DateField()),
                ('selected_time', models.CharField(max_length=16)),
                ('total_amount_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='new', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(default='site', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('item_external_id', models.CharField(blank=True, max_length=32)),
                ('item_slug', models.SlugField(blank=True, max_length=255)),
                ('item_title', models.CharField(blank=True, max_length=255)),
                ('item_type', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('education_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='content.educationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
