# Generated by Django 6.0.6 on 2026-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationregistration',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
