# Generated by Django 5.2.16 on 2026-07-25 15:38

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_chat_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('consultation_followup', 'Consultation follow-up'), ('education_support', 'Education support'), ('feedback_followup', 'Feedback follow-up'), ('documents', 'Documents'), ('general', 'General')], default='general', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('waiting_client', 'Waiting client'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_model', models.CharField(blank=True, max_length=64)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('lost', 'Lost')], default='new', max_length=32)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_client_profile_email_lower')],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='interactions.aftersalescase')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='interactions.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aftersalescase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='interactions.clientprofile'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['status', 'priority'], name='as_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['source_model', 'source_id'], name='as_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftersalescase',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_model', ''), _negated=True), ('source_id__isnull', False)), fields=('source_model', 'source_id'), name='unique_after_sales_source'),
        ),
    ]
